# Generated by Django 2.1.1 on 2018-09-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world_app', '0002_auto_20180919_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='author',
            field=models.TextField(default='no author', max_length=100),
        ),
        migrations.AddField(
            model_name='graph',
            name='tags',
            field=models.TextField(blank=True),
        ),
    ]
