# Generated by Django 2.1.1 on 2018-09-19 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hello_world_app', '0003_auto_20180919_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphWithUser',
            fields=[
                ('graph_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hello_world_app.Graph')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('hello_world_app.graph',),
        ),
    ]
